# ================================================================================
# RECURSIVE THINKING WEBSITE - SERVERLESS TEMPLATE
# ================================================================================

AWSTemplateFormatVersion: 2010-09-09
Parameters:
  AssetsS3Bucket:
    Type: String

  UserAssetsS3Bucket:
    Type: String

  LambdaFolder:
    Description: Folder that contains Backend Lambda code
    MaxLength: 60
    MinLength: 5
    Type: String

Resources:
  # ================================================================================

  # AWS::IAM::Role

  # Any IAM roles can be attached to AWS entities.  It allows stuff we create in AWS priviledges and boundries of what they are allowed to do.  So we have can scope these down as much as we want, or give our resources as much privileges as well. mostly security stuff but also super annoying because stuff wont work alot of times its the IAM priviledges to blame.

  # ================================================================================

  RTWIAMRoleLambda:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "lambda.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: "root"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action: "*"
                Resource: "*"
      RoleName: "RTW_IAMRoleLambda"

  # ================================================================================

  # AWS::Cognito::UserPool

  # Heres our Cognito User Pool, We can set all the properties to configure how we store/verify users.  This will essentially be our AUTH. it doesn't need to store user data just their email/password so we can Auth them to use our service.

  # ================================================================================

  RecursiveThinkingUserPool:
    Type: "AWS::Cognito::UserPool"
    Properties:
      AutoVerifiedAttributes:
        - email
      EmailVerificationMessage: "Welcome! Please paste this code: {####} into the modal to confirm your account with Recursive Thinking"
      EmailVerificationSubject: Verification of Recursive Thinking Profile
      Policies:
        PasswordPolicy:
          MinimumLength: 6
          RequireLowercase: False
          RequireNumbers: False
          RequireSymbols: False
          RequireUppercase: False
      UserPoolName: RecursiveThinkingUserPool
      Schema:
        - Name: name
          AttributeDataType: String
          Mutable: false
          Required: true
        - Name: email
          AttributeDataType: String
          Mutable: false
          Required: true
      UserPoolTags: { "project": "RecursiveThinkingWebsite" }

  # ================================================================================

  # AWS::Cognito::UserPoolClient

  # This is essentially our Web App which is a client of our user pool.  We can define the refresh token validity and thats about it. We need the ID of this client to connect to our user pool (see outputs section at bottom).

  # ================================================================================

  RecursiveThinkingUserPoolClient:
    Type: "AWS::Cognito::UserPoolClient"
    Properties:
      ClientName: RTW
      GenerateSecret: False
      RefreshTokenValidity: 30
      UserPoolId: !Ref RecursiveThinkingUserPool

  # ----------------------------------------------------------------------
  # Creates the Federated Identity Pool -
  # TUsed specifically to allow users to upload to s3
  # ----------------------------------------------------------------------

  RecursiveThinkingIdentityPoolForS3:
    Type: "AWS::Cognito::IdentityPool"
    Properties:
      IdentityPoolName: "RecursiveThinkingIdentityPoolForS3"
      AllowUnauthenticatedIdentities: true
      CognitoIdentityProviders:
        - ClientId: !Ref RecursiveThinkingUserPoolClient
          ProviderName: !GetAtt RecursiveThinkingUserPool.ProviderName

  # ----------------------------------------------------------------------
  # Create a role for unauthorized access to AWS resources. Very limited access. Only allows users in the previously created Identity Pool
  # ----------------------------------------------------------------------

  CognitoUnAuthorizedRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Federated: "cognito-identity.amazonaws.com"
            Action:
              - "sts:AssumeRoleWithWebIdentity"
            Condition:
              StringEquals:
                "cognito-identity.amazonaws.com:aud": !Ref RecursiveThinkingIdentityPoolForS3
              "ForAnyValue:StringLike":
                "cognito-identity.amazonaws.com:amr": unauthenticated
      Policies:
        - PolicyName: "CognitoUnauthorizedPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "mobileanalytics:PutEvents"
                  - "cognito-sync:*"
                  - "s3:*"
                Resource:
                  - "*"
                  - !Join ["", ["arn:aws:s3:::", !Ref UserAssetsS3Bucket, "/*"]]

  CognitoAuthorizedRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Federated: "cognito-identity.amazonaws.com"
            Action:
              - "sts:AssumeRoleWithWebIdentity"
            Condition:
              StringEquals:
                "cognito-identity.amazonaws.com:aud": !Ref RecursiveThinkingIdentityPoolForS3
              "ForAnyValue:StringLike":
                "cognito-identity.amazonaws.com:amr": authenticated
      Policies:
        - PolicyName: "CognitoAuthorizedPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "mobileanalytics:PutEvents"
                  - "cognito-sync:*"
                  - "cognito-identity:*"
                Resource: "*"

  # ----------------------------------------------------------------------
  # Assigns the roles to the Identity Pool
  # ----------------------------------------------------------------------

  RecursiveThinkingIdentityPoolRoleMapping:
    Type: "AWS::Cognito::IdentityPoolRoleAttachment"
    Properties:
      IdentityPoolId: !Ref RecursiveThinkingIdentityPoolForS3
      Roles:
        authenticated: !GetAtt CognitoAuthorizedRole.Arn
        unauthenticated: !GetAtt CognitoUnAuthorizedRole.Arn

  # ================================================================================
  # S3 Bucket - To Store Resumes and Avatars per user
  # ================================================================================

  RecursiveThinkingUserAssetsS3Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      AccessControl: PublicReadWrite
      BucketName: !Ref UserAssetsS3Bucket
      CorsConfiguration:
        CorsRules:
          - AllowedOrigins:
              - "*"
            AllowedMethods:
              - HEAD
              - GET
              - POST
              - PUT
              - DELETE
            AllowedHeaders:
              - "*"
      Tags:
        - Key: project
          Value: RecursiveThinkingWebsite

# ================================================================================

# CLOUDFORMATION STACK - OUTPUTS

# These are our outputs to show after running our python script, available in the stack_response

# We can paste the cognito clientId and cognitoUserPoolId in main.js of our webapp to connect to that specific resource with AWS Amplify library (our auth).

# We can use the API Gateway ID as the base of the URL that we make all our api calls to. This allows us to set these values when we want to test on one 'stack' or instance of the architecture in this template.

# (NOT IMPLEMENTED YET) We will have a 'beta' stack and a 'prod' stack.

# Allows us to change these values in the webapp when we want to test things out and not break the 'prod' stack.

# Which stack gets built and what is output is specified by passing the --stage beta or --stage '' to our Python script. For now just dont pass --stage because stuffs not in production yet.

# ================================================================================

Outputs:
  CognitoUserPoolId:
    Description: userPoolId - The cognito user pool id
    Value: !Ref RecursiveThinkingUserPool
    Export:
      Name: CognitoUserPoolIdentifier

  CognitoClientId:
    Description: userPoolWebClientId - The id of the client (app) connected to cognito
    Value: !Ref RecursiveThinkingUserPoolClient
    Export:
      Name: CognitoUserPoolClientIdentifier

  CognitoIdentityPoolId:
    Description: IdentityPoolId - Export for s3 Bucket
    Value: !Ref RecursiveThinkingIdentityPoolForS3
    Export:
      Name: "RecursiveThinkingIdentityPoolForS3::Id"

  s3BucketName:
    Description: s3BucketName - Name of s3 Bucket
    Value: !Ref RecursiveThinkingUserAssetsS3Bucket
    Export:
      Name: "s3BucketName"
